//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Cms.Web.PropertyEditors.RichTextBox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RichTextBoxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RichTextBoxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Cms.Web.PropertyEditors.RichTextBox.Resources.RichTextBoxResources", typeof(RichTextBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;features&gt;
        ///  &lt;feature name=&quot;Highlight&quot; alias=&quot;backcolor&quot; /&gt;
        ///  &lt;feature name=&quot;Bold&quot; alias=&quot;bold&quot; /&gt;
        ///  &lt;feature name=&quot;Bulleted List&quot; alias=&quot;bullist&quot; /&gt;
        ///  &lt;feature name=&quot;Numbered List&quot; alias=&quot;numlist&quot; /&gt;
        ///  &lt;feature name=&quot;Symbols&quot; alias=&quot;umbracocharmap&quot; /&gt;
        ///  &lt;feature name=&quot;Cleanup&quot; alias=&quot;cleanup&quot; /&gt;
        ///  &lt;feature name=&quot;Html&quot; alias=&quot;code&quot; /&gt;
        ///  &lt;feature name=&quot;Copy&quot; alias=&quot;copy&quot; /&gt;
        ///  &lt;feature name=&quot;Cut&quot; alias=&quot;cut&quot; /&gt;
        ///  &lt;feature name=&quot;Help&quot; alias=&quot;help&quot; /&gt;
        ///  &lt;featu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeaturesList {
            get {
                return ResourceManager.GetString("FeaturesList", resourceCulture);
            }
        }
    }
}
