//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Cms.Packages.DevDataset {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Cms.Packages.DevDataset.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE root[ 
        ///&lt;!ELEMENT faq ANY&gt;
        ///&lt;!ATTLIST faq id ID #REQUIRED&gt;
        ///&lt;!ELEMENT faqCategory ANY&gt;
        ///&lt;!ATTLIST faqCategory id ID #REQUIRED&gt;
        ///&lt;!ELEMENT faqQuestion ANY&gt;
        ///&lt;!ATTLIST faqQuestion id ID #REQUIRED&gt;
        ///&lt;!ELEMENT Homepage ANY&gt;
        ///&lt;!ATTLIST Homepage id ID #REQUIRED&gt;
        ///&lt;!ELEMENT Textpage ANY&gt;
        ///&lt;!ATTLIST Textpage id ID #REQUIRED&gt;
        ///
        ///]&gt;
        ///&lt;root id=&quot;-2&quot;&gt;
        ///  &lt;Homepage id=&quot;1048&quot; parentID=&quot;-2&quot; level=&quot;1&quot; writerID=&quot;0&quot; creatorID=&quot;0&quot; nodeType=&quot;1045&quot; template=&quot;Homepage.cshtml&quot; sort [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string umbraco {
            get {
                return ResourceManager.GetString("umbraco", resourceCulture);
            }
        }
    }
}
